import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbars from "@/components/Navbars";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full bg-white px-2 md:px-8 lg:px-16 xl:px-32 2xl:px-64 ">
          <Navbars />
        </div>
        <div className="bg-slate-100 px-2 md:px-8 lg:px-16 xl:px-32 2xl:px-64 ">
          {children}
        </div>
      </body>
    </html>
  );
}
